image: "python:3.8"

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Static Analysis
    - Test

flake8:
    stage: Static Analysis
    script:
        - flake8

mypy:
    stage: Static Analysis
    script:
        - mypy .

pytest:
    stage: Test
    script:
        - python -m pytest
